spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.198.194.12:3306/log?allowMultiQueries:true&autoReconnect:true
    username: develop
    password: viprz
    driverClassName: com.mysql.jdbc.Driver
    # dataSource Pool configuration
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    # exceptionSorter:true
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:500;druid.stat.logSlowSql:true;
    useGlobalDataSourceStat: true

  mybatis:
    mapper-locations: classpath*:mapper/*.xml
    check-config-location: true
    type-aliases-package: com.biz.tcc.common.repository